import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.jumia.ug/');
  await page.getByRole('button', { name: 'newsletter_popup_close-cta' }).click();
  await page.locator('label').filter({ hasText: 'Account' }).getByRole('img').nth(1).click();
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.goto('https://my.jumia.ug/interaction/qtYpQUCx1F--rdr6lhpoL/en-ug/identification');
  await page.locator('#input_identifierValue').click();
  await page.locator('#input_identifierValue').fill('0701263898');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('CHes1@jumia');
  await page.locator('label').getByRole('button').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByLabel('sms').click();
  await page.locator('div').filter({ hasText: 'Send OTP' }).nth(3).click();
  await page.goto('https://my.jumia.ug/interaction/qtYpQUCx1F--rdr6lhpoL/en-ug/sms-captcha#otp');
  await page.frameLocator('iframe[title="Widget containing a Cloudflare security challenge"]').getByLabel('Verify you are human').check();
  await page.locator('div').filter({ hasText: 'Verify you are not a BOT' }).nth(1).click();
  await page.goto('https://my.jumia.ug/interaction/qtYpQUCx1F--rdr6lhpoL/en-ug/sms-captcha#otp');
  await page.goto('https://my.jumia.ug/interaction/qtYpQUCx1F--rdr6lhpoL/en-ug/sms-captcha');
  await page.goto('https://my.jumia.ug/interaction/qtYpQUCx1F--rdr6lhpoL/en-ug/identification');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('CHes1@jumia');
  await page.locator('label').getByRole('button').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByLabel('digit 1').click();
  await page.getByLabel('digit 1').fill('777');
  await page.getByLabel('digit 2').click();
  await page.getByLabel('digit 2').click();
  await page.getByLabel('digit 2').fill('7');
  await page.getByLabel('digit 1').click();
  await page.getByLabel('digit 1').fill('7');
  await page.getByLabel('digit 2').fill('3');
  await page.getByLabel('digit 3').fill('6');
  await page.getByLabel('digit 4').fill('3');
  await page.goto('https://www.jumia.ug/');
  await page.locator('label').filter({ hasText: 'Hi, Obeke' }).getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});