import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://www.jumia.ug/');
  await page.locator('label').filter({ hasText: 'Account' }).getByRole('img').nth(1).click();
  await page.goto('https://my.jumia.ug/interaction/4KqWQ5N5QGOKC30aTsCD6/en-ug/browser-check');
  await page.goto('https://my.jumia.ug/interaction/4KqWQ5N5QGOKC30aTsCD6/en-ug/identification');
  await page.locator('#input_identifierValue').click();
  await page.locator('#input_identifierValue').fill('0701263898');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('CHes1@jumia');
  await page.locator('label').getByRole('button').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByLabel('digit 1').fill('2');
  await page.getByLabel('digit 2').fill('3');
  await page.getByLabel('digit 3').fill('6');
  await page.getByLabel('digit 4').fill('0');
  await page.getByRole('button', { name: 'Skip for now' }).click();
  await page.goto('https://www.jumia.ug/');
  await page.getByRole('menuitem', { name: 'TVs & Audio' }).click();
  await page.getByRole('link', { name: 'Vision Plus 55 Inch 4K' }).click();
  await page.locator('#add-to-cart').getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('link', { name: 'Electronics>' }).click();
  await page.getByRole('link', { name: 'SPJ 3.1 Channel Home Audio' }).first().click();
  await page.locator('#add-to-cart').getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('link', { name: 'Electronics>' }).click();
  await page.getByRole('link', { name: 'd.light SF31 AC/DC Fan With' }).click();
  await page.locator('#add-to-cart').getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('link', { name: 'Electronics>' }).click();
  await page.getByRole('link', { name: 'to 42 TV Wall Mount & 4 Way Extension Cable - Black, White UGX 28,900 UGX 57,000 - 49% 3 out of 5 (1)' }).click();
  await page.locator('#add-to-cart').getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('link', { name: 'Cart' }).click();
  await page.locator('article').filter({ hasText: /^Liberty Protect - Device InsuranceIn StockUGX 44,500Remove1$/ }).getByRole('button').first().click();
  await page.getByRole('button', { name: 'Remove Item' }).click();
  await page.getByRole('link', { name: 'Checkout (UGX 1,507,894)' }).click();
  await page.getByText('Confirm order(Complete the').click();
  await page.getByText('Confirm order(Complete the').click();
  await page.getByRole('button', { name: 'Select pickup station' }).click();
  await page.getByLabel('City').selectOption('96');
  await page.getByLabel('Select a Pick-up station').getByRole('button', { name: 'Select pickup station' }).click();
  await page.getByRole('link', { name: 'Change' }).click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByLabel('City').selectOption('96');
  await page.goto('https://www.jumia.ug/checkout/shipping-options/');
  await page.getByRole('link', { name: 'Jumia Uganda | Online' }).click();
  await page.locator('label').filter({ hasText: 'Hi, Obeke' }).getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.goto('https://www.jumia.ug/');
});